
unwarp( ...
	'/repo/thaltrack-whole/src/testdir/OUTPUTS/iy_invdef.nii.gz', ...
	'/repo/thaltrack-whole/src/testdir/OUTPUTS/nu.nii.gz', ...
	'/repo/thaltrack-whole/src/external/yeo_networks/Yeo17_split.nii.gz', ...
	'/repo/thaltrack-whole/src/testdir/OUTPUTS' ...
	)
